### ISSUE TITLE
Coverage and coveralls in install requirements

### ISSUE THREAD

**Issue by awvwgk** [symmy596/SurfinPy#20]
Is there a reason to require [coverage](https://coverage.readthedocs.io/en/6.2/) and [coveralls](https://coveralls-python.readthedocs.io/en/latest/) for installation of this project? Those seem more suitable as test requirements for the continuous integration rather than a user installation.

**Comment by jstse** [comment]
Removed coverage and coveralls from installation requirments.  See pull request for more information #27
