### ISSUE TITLE
Jupyter in install requirements

### ISSUE THREAD

**Issue by awvwgk** [symmy596/SurfinPy#22]
The install requirements in setup.py list Jupyter, however this is not listed in the README.

**Comment by jstse** [comment]
The examples we provide are created using jupyter notebooks and we feel for new user experience having jupyter would be a requirement.

**Comment by awvwgk** [comment]
Jupyter is not crucial for the functionality of the package, therefore it doesn't qualify as an install requirement. For optional dependencies there is a dedicated mechanism in setup.py which allows installations with features (*i.e.* `pip install .[jupyter]`).

**Comment by jstse** [comment]
Thank you for informing me of this feature.
I have no added jupyter to an optional extra under a Tutorials install and have updated the Readme with install instructions.
