### ISSUE TITLE
PyPI releases mismatch tags?

### ISSUE THREAD

**Issue by awvwgk** [symmy596/SurfinPy#25]
What is the relation between the releases/tags in this repo (https://github.com/symmy596/SurfinPy/tags) and the releases available on PyPI (https://pypi.org/project/surfinpy/#history). There are several versions appearing on PyPI which are not tagged in this repository.

**Comment by jstse** [comment]
@symmy596 should now have fixed this issue

**Comment by awvwgk** [comment]
Thanks. Somewhat scary that you just unpublish stuff from PyPI, though.

BTW, I put up a feedstock on cf: https://github.com/conda-forge/surfinpy-feedstock.
