### ISSUE TITLE
Installation fails due to conflicting coverage version

### ISSUE THREAD

**Issue by NeolithEra** [symmy596/SurfinPy#7]
Hi, users are unable to run **_surfinpy_** due to dependency conflict with _**coverage**_ package. As shown in the following full dependency graph of **_surfinpy_**, **_surfinpy_** requires **_coverage *_**，while **_coveralls_** requires **_coverage <5.0,>=3.6_**.

According to pip’s _“first found wins”_ installation strategy, _**coverage 5.0**_ is the actually installed version. However, _**coverage 5.0**_ does not satisfy **_<5.0,>=3.6_**.

### Dependency tree-----------
```
surfinpy - 1.0.2
| +- coverage(install version:5.0 version range:*)
| +- coveralls(install version:1.9.2 version range:*)
| | +- coverage(install version:4.5.4 version range:<5.0,>=3.6)
| +- jupyter(install version:1.0.0 version range:*)
| +- matplotlib(install version:3.2.0rc1 version range:*)
| | +- cycler(install version:0.10.0 version range:>=0.10)
| | | +- six(install version:1.13.0 version range:*)
| | +- kiwisolver(install version:1.1.0 version range:>=1.0.1)
| | | +- setuptools(install version:42.0.2 version range:*)
| | +- numpy(install version:1.18.0rc1 version range:>=1.11)
| | +- pyparsing(install version:2.4.5 version range:>=2.0.1)
| | +- python-dateutil(install version:2.8.1 version range:>=2.1)
| +- numpy(install version:1.18.0rc1 version range:*)
| +- pymatgen(install version:2019.12.3 version range:*)
| +- scipy(install version:1.4.1 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependency to be **_coverage<5.0_**. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_coveralls_** to loose the version range of **_coverage_**.
3.	Remove your direct dependency **_coverage_**, and use **_coverage_** transitively introduced by **_coveralls_**.

@symmy596 Which solution do you prefer, 1, 2 or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by symmy596** [comment]
Solution 3 seems appropriate. PR would be greatly appreciated. 

Cheers
